### ISSUE TITLE
DayPlan Client-side

### ISSUE THREAD

**Issue by DTasev** [DTasev/dawdle-client#73]
- Client support to:
  - Tell the user which task they're working on
  - Tell the user how much time is left from the **allocated** time for the task
  - Specify the DayTask in the Period data, so that it is automatically added (the functionality in `daytask/addperiod/<int:pk>` but through an API for the client)
- If a DayTask already has a period do one of:
  - Filter out in the API `serializers/day_planner.py -> get_tasks()`
  - Send via API but grey out in client (does this make sense? Maybe an option to visit the Day URL could be provided)

# Tasks
- Query `api/v1/day/`
  - [x] if 404 then there is no day
  - [x] if 200 then display tasks to the user
- [x] Display notes on task double click
- [x] Auto query after startup
- [x] Display loading icon of some sort in the list item (maybe a list item `Loading...`?)
- [x] Check why the daytask wasn't assigned the period (django)

<details>

![image](https://user-images.githubusercontent.com/9135965/40453496-45c16ca2-5edd-11e8-8b8a-dc375481c384.png)

</details>
