### ISSUE TITLE
Editing tasks' notes

### ISSUE THREAD

**Issue by DTasev** [DTasev/dawdle-client#77]
- [x] Edit task notes locally and save them
- [x] Note editing window's title should be the `name of the task - Notes` or similar
- ~Note editing window can currently be opened many times. This shouldn't be possible~
- [x] Show visual identifier that the task notes have been saved (like tickbox in save button?)
- [x] Make Shift+Enter save the task notes

# Todo
- [x] Test JSONBuilder
- [x] Test setting daytask id on `Period.Stop`
